// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nhite.proto

/*
Package pbnhite is a generated protocol buffer package.

It is generated from these files:
	nhite.proto

It has these top-level messages:
	Body
	Id
	Arg
	Output
*/
package pbnhite

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Body struct {
	Zipfile []byte `protobuf:"bytes,1,opt,name=zipfile,proto3" json:"zipfile,omitempty"`
}

func (m *Body) Reset()                    { *m = Body{} }
func (m *Body) String() string            { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()               {}
func (*Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Body) GetZipfile() []byte {
	if m != nil {
		return m.Zipfile
	}
	return nil
}

type Id struct {
	Tmpdir string `protobuf:"bytes,1,opt,name=tmpdir" json:"tmpdir,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Id) GetTmpdir() string {
	if m != nil {
		return m.Tmpdir
	}
	return ""
}

// The request message containing the user's name.
type Arg struct {
	WorkingDir string   `protobuf:"bytes,1,opt,name=workingDir" json:"workingDir,omitempty"`
	Args       []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *Arg) Reset()                    { *m = Arg{} }
func (m *Arg) String() string            { return proto.CompactTextString(m) }
func (*Arg) ProtoMessage()               {}
func (*Arg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Arg) GetWorkingDir() string {
	if m != nil {
		return m.WorkingDir
	}
	return ""
}

func (m *Arg) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

// The response message containing the greetings
type Output struct {
	Retcode int32  `protobuf:"varint,1,opt,name=retcode" json:"retcode,omitempty"`
	Stdout  []byte `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr  []byte `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Output) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *Output) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *Output) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func init() {
	proto.RegisterType((*Body)(nil), "pbnhite.Body")
	proto.RegisterType((*Id)(nil), "pbnhite.Id")
	proto.RegisterType((*Arg)(nil), "pbnhite.Arg")
	proto.RegisterType((*Output)(nil), "pbnhite.Output")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Terraform service

type TerraformClient interface {
	Init(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error)
	Plan(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error)
	Apply(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error)
	Push(ctx context.Context, opts ...grpc.CallOption) (Terraform_PushClient, error)
}

type terraformClient struct {
	cc *grpc.ClientConn
}

func NewTerraformClient(cc *grpc.ClientConn) TerraformClient {
	return &terraformClient{cc}
}

func (c *terraformClient) Init(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := grpc.Invoke(ctx, "/pbnhite.Terraform/Init", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terraformClient) Plan(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := grpc.Invoke(ctx, "/pbnhite.Terraform/Plan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terraformClient) Apply(ctx context.Context, in *Arg, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := grpc.Invoke(ctx, "/pbnhite.Terraform/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terraformClient) Push(ctx context.Context, opts ...grpc.CallOption) (Terraform_PushClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Terraform_serviceDesc.Streams[0], c.cc, "/pbnhite.Terraform/Push", opts...)
	if err != nil {
		return nil, err
	}
	x := &terraformPushClient{stream}
	return x, nil
}

type Terraform_PushClient interface {
	Send(*Body) error
	CloseAndRecv() (*Id, error)
	grpc.ClientStream
}

type terraformPushClient struct {
	grpc.ClientStream
}

func (x *terraformPushClient) Send(m *Body) error {
	return x.ClientStream.SendMsg(m)
}

func (x *terraformPushClient) CloseAndRecv() (*Id, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Id)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Terraform service

type TerraformServer interface {
	Init(context.Context, *Arg) (*Output, error)
	Plan(context.Context, *Arg) (*Output, error)
	Apply(context.Context, *Arg) (*Output, error)
	Push(Terraform_PushServer) error
}

func RegisterTerraformServer(s *grpc.Server, srv TerraformServer) {
	s.RegisterService(&_Terraform_serviceDesc, srv)
}

func _Terraform_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerraformServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbnhite.Terraform/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerraformServer).Init(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Terraform_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerraformServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbnhite.Terraform/Plan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerraformServer).Plan(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Terraform_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Arg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerraformServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbnhite.Terraform/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerraformServer).Apply(ctx, req.(*Arg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Terraform_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TerraformServer).Push(&terraformPushServer{stream})
}

type Terraform_PushServer interface {
	SendAndClose(*Id) error
	Recv() (*Body, error)
	grpc.ServerStream
}

type terraformPushServer struct {
	grpc.ServerStream
}

func (x *terraformPushServer) SendAndClose(m *Id) error {
	return x.ServerStream.SendMsg(m)
}

func (x *terraformPushServer) Recv() (*Body, error) {
	m := new(Body)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Terraform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbnhite.Terraform",
	HandlerType: (*TerraformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Terraform_Init_Handler,
		},
		{
			MethodName: "Plan",
			Handler:    _Terraform_Plan_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Terraform_Apply_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _Terraform_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "nhite.proto",
}

func init() { proto.RegisterFile("nhite.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xbd, 0x6a, 0xc3, 0x30,
	0x14, 0x85, 0xe3, 0x9f, 0x38, 0xf8, 0x26, 0xa5, 0xa0, 0xa1, 0x88, 0x50, 0x8a, 0xd1, 0xd0, 0x7a,
	0xf2, 0xd0, 0x4e, 0x1d, 0x5d, 0xba, 0x78, 0x6a, 0x10, 0x7d, 0x01, 0xa7, 0x52, 0x1c, 0x51, 0xc7,
	0x12, 0xd7, 0x32, 0x25, 0x7d, 0xa9, 0xbe, 0x62, 0xb1, 0xe2, 0x88, 0x6c, 0xd9, 0xf4, 0x9d, 0x7b,
	0xe0, 0x93, 0x74, 0x61, 0xd9, 0xed, 0x95, 0x95, 0x85, 0x41, 0x6d, 0x35, 0x59, 0x98, 0xad, 0x43,
	0x96, 0x41, 0xfc, 0xa6, 0xc5, 0x91, 0x50, 0x58, 0xfc, 0x2a, 0xb3, 0x53, 0xad, 0xa4, 0x41, 0x16,
	0xe4, 0x2b, 0x7e, 0x46, 0x76, 0x0f, 0x61, 0x25, 0xc8, 0x1d, 0x24, 0xf6, 0x60, 0x84, 0x42, 0x37,
	0x4e, 0xf9, 0x44, 0xec, 0x15, 0xa2, 0x12, 0x1b, 0xf2, 0x00, 0xf0, 0xa3, 0xf1, 0x5b, 0x75, 0xcd,
	0xbb, 0xaf, 0x5c, 0x24, 0x84, 0x40, 0x5c, 0x63, 0xd3, 0xd3, 0x30, 0x8b, 0xf2, 0x94, 0xbb, 0x33,
	0xe3, 0x90, 0x7c, 0x0c, 0xd6, 0x0c, 0x76, 0x94, 0xa3, 0xb4, 0x5f, 0x5a, 0x9c, 0xe4, 0x73, 0x7e,
	0xc6, 0x51, 0xdb, 0x5b, 0xa1, 0x07, 0x4b, 0x43, 0x77, 0xab, 0x89, 0xa6, 0x5c, 0x22, 0xd2, 0xc8,
	0xe7, 0x12, 0xf1, 0xf9, 0x2f, 0x80, 0xf4, 0x53, 0x22, 0xd6, 0x3b, 0x8d, 0x07, 0xf2, 0x04, 0x71,
	0xd5, 0x29, 0x4b, 0x56, 0xc5, 0xf4, 0xdc, 0xa2, 0xc4, 0x66, 0x7d, 0xeb, 0xe9, 0xa4, 0x67, 0xb3,
	0xb1, 0xb8, 0x69, 0xeb, 0xee, 0x7a, 0x31, 0x87, 0x79, 0x69, 0x4c, 0x7b, 0xbc, 0xde, 0x7c, 0x84,
	0x78, 0x33, 0xf4, 0x7b, 0x72, 0xe3, 0x47, 0xe3, 0x3f, 0xaf, 0x97, 0x1e, 0x2b, 0xc1, 0x66, 0x79,
	0xb0, 0x4d, 0xdc, 0x42, 0x5e, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x3b, 0xd7, 0x62, 0x9f,
	0x01, 0x00, 0x00,
}
